# Generated by Django 5.2.6 on 2025-12-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_gymmachine"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("start", "사용 시작"), ("end", "사용 종료")], max_length=10
                    ),
                ),
                ("image", models.ImageField(upload_to="events/%Y/%m/%d/")),
                ("captured_at", models.DateTimeField(help_text="Edge에서 캡처한 시각")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("person_count", models.IntegerField(default=0)),
                (
                    "detections",
                    models.JSONField(default=dict, help_text="YOLO 검출 결과 JSON"),
                ),
                (
                    "change_info",
                    models.JSONField(
                        default=dict, help_text="Change Detection 결과 JSON"
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="blog.gymmachine",
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["machine", "-captured_at"],
                        name="blog_machin_machine_41617d_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-captured_at"],
                        name="blog_machin_event_t_522aea_idx",
                    ),
                ],
            },
        ),
    ]
