# Generated by Django 5.2.6 on 2025-12-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_apiuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("treadmill", "런닝머신"),
                            ("bench_press", "벤치프레스"),
                            ("squat_rack", "스쿼트랙"),
                            ("lat_pulldown", "랫풀다운"),
                            ("leg_press", "레그프레스"),
                            ("cable_machine", "케이블머신"),
                            ("dumbbell", "덤벨존"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(help_text="예: 1층 A구역", max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="machines/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["location", "name"],
            },
        ),
    ]
